# Generated by Django 4.2.3 on 2023-07-08 16:20

from django.db import migrations, models
import django.db.models.deletion
import server.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to=server.models.upload_to)),
            ],
            options={
                'verbose_name_plural': 'Files',
            },
        ),
        migrations.CreateModel(
            name='FileActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloads', models.PositiveIntegerField(default=0)),
                ('emailed', models.PositiveIntegerField(default=0)),
                ('file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='server.files')),
            ],
        ),
    ]
