# Generated by Django 4.2.3 on 2023-07-08 16:46

from django.db import migrations, models
import server.models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileactivity',
            options={'verbose_name_plural': 'File Activity'},
        ),
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(upload_to=server.models.upload_to('files')),
        ),
    ]
