# Generated by Django 4.2.3 on 2023-07-13 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_alter_fileactivity_options_alter_files_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileactivity',
            name='id',
        ),
        migrations.AlterField(
            model_name='fileactivity',
            name='file',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='file_activity', serialize=False, to='server.files'),
        ),
    ]
