# Generated by Django 4.2.3 on 2023-07-13 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_alter_fileactivity_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileactivity',
            name='file',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='file_activity', to='server.files'),
        ),
    ]
