# Generated by Django 4.2.3 on 2023-07-13 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_alter_fileactivity_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='number_of_downloads',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='files',
            name='number_of_emails',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='FileActivity',
        ),
    ]
